version: '3.8'

services:
  hackman-v8-frontend:
    image: slashex/hackermanv8:latest
    container_name: hackman-v8-frontend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - hackman-network

networks:
  hackman-network:
    driver: bridge
